### ISSUE TITLE
Unwanted text on the homepage

### ISSUE THREAD

**Issue by dannyparsons** [IDEMSInternational/virtual-maths-camp-gh-pages#5]
The [latest commit](https://github.com/IDEMSInternational/virtual-maths-camp-gh-pages/commit/913e779799734628dae5d2fdca48d848d259673c) has introduced some unwanted text on the homepage. See below.

![image](https://user-images.githubusercontent.com/11214914/88278405-373e7b80-ccda-11ea-8e54-8fc1c6a314fe.png)

There is also some hidden white text under the images that says "Ghana camp students" that you can see if you highlight it. That seemed to be there before the latest commit:

![image](https://user-images.githubusercontent.com/11214914/88278471-550be080-ccda-11ea-807f-aa53a57376f8.png)

**Comment by laetitiaCA** [comment]
Removed the unwanted text.

**Comment by dannyparsons** [comment]
That's great. In your commit or pull request message if you included "fixes #5" then you can link the commit/pull request to the issue being resolved and this also closes the issue automatically when the commit/pull request is merged.

**Comment by dannyparsons** [comment]
I still see the hidden text under the images for some of the images. Also, some of the images now seem to not appear.

**Comment by laetitiaCA** [comment]
fixes #5 The text are captions with brief description of each picture, will either enlarge the text to make it more visible/pronounced or remove them entirely.
