### ISSUE TITLE
Update IDEMS Logo

### ISSUE THREAD

**Issue by dannyparsons** [IDEMSInternational/virtual-maths-camp-gh-pages#8]
IDEMS now has a new logo (attached). Could this go up on the website to replace the old one?

[idems-logo.zip](https://github.com/IDEMSInternational/virtual-maths-camp-gh-pages/files/5035829/idems-logo.zip)

**Comment by laetitiaCA** [comment]
Assigned #8 resolved: IDEMS logo updated.

**Comment by dannyparsons** [comment]
Great thanks! 
You don't need to tag the issue number here to close it, but do this in your commit message or pull request comment when you submit the code changes. 
For example, in your commit here: https://github.com/IDEMSInternational/virtual-maths-camp-gh-pages/commit/1e1e75adefc2a6667f59f57e58af16c7d634b5fb you could have added to the commit message something like "update idems logo fixes #8"
It's not necessary to do this but it's just a nice feature of GitHub that it then clearly links the code changes to the issue being worked on.

**Comment by laetitiaCA** [comment]
Ok, thanks!
